// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.12
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:149

#ifndef _TAO_IDL_INSTRUCTIONTYPESUPPORTC_7OLOBG_H_
#define _TAO_IDL_INSTRUCTIONTYPESUPPORTC_7OLOBG_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "instructionC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 12
#error This file should be regenerated with TAO_IDL
#endif

// TAO_IDL - Generated from
// d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:35

namespace instruction
{

  // TAO_IDL - Generated from
  // d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_sequence\sequence_ch.cpp:99

  typedef ::TAO::DCPS::ZeroCopyDataSeq< instruction::instruct, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> instructSeq;
  

  // TAO_IDL - Generated from
  // d:\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_INSTRUCTION_INSTRUCTTYPESUPPORT__VAR_OUT_CH_)
#define _INSTRUCTION_INSTRUCTTYPESUPPORT__VAR_OUT_CH_

  class instructTypeSupport;
  typedef instructTypeSupport *instructTypeSupport_ptr;
  typedef TAO_Objref_Var_T<instructTypeSupport> instructTypeSupport_var;
  typedef TAO_Objref_Out_T<instructTypeSupport> instructTypeSupport_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  instructTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef instructTypeSupport_ptr _ptr_type;
    typedef instructTypeSupport_var _var_type;
    typedef instructTypeSupport_out _out_type;

    // The static operations.
    static instructTypeSupport_ptr _duplicate (instructTypeSupport_ptr obj);

    static void _tao_release (instructTypeSupport_ptr obj);

    static instructTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static instructTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static instructTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    instructTypeSupport (void);

    

    virtual ~instructTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (instructTypeSupport (const instructTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (instructTypeSupport (instructTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (instructTypeSupport &operator= (const instructTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (instructTypeSupport &operator= (instructTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // d:\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_INSTRUCTION_INSTRUCTDATAWRITER__VAR_OUT_CH_)
#define _INSTRUCTION_INSTRUCTDATAWRITER__VAR_OUT_CH_

  class instructDataWriter;
  typedef instructDataWriter *instructDataWriter_ptr;
  typedef TAO_Objref_Var_T<instructDataWriter> instructDataWriter_var;
  typedef TAO_Objref_Out_T<instructDataWriter> instructDataWriter_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  instructDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef instructDataWriter_ptr _ptr_type;
    typedef instructDataWriter_var _var_type;
    typedef instructDataWriter_out _out_type;

    // The static operations.
    static instructDataWriter_ptr _duplicate (instructDataWriter_ptr obj);

    static void _tao_release (instructDataWriter_ptr obj);

    static instructDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static instructDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static instructDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::instruction::instruct & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::instruction::instruct & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::instruction::instruct & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::instruction::instruct & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::instruction::instruct & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::instruction::instruct & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::instruction::instruct & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::instruction::instruct & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::instruction::instruct & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::instruction::instruct & instance_data) = 0;

    // TAO_IDL - Generated from
    // d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    instructDataWriter (void);

    

    virtual ~instructDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (instructDataWriter (const instructDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (instructDataWriter (instructDataWriter &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (instructDataWriter &operator= (const instructDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (instructDataWriter &operator= (instructDataWriter &&))
#endif /* ACE_HAS_CPP11 */
  };

  // TAO_IDL - Generated from
  // d:\opendds\ace_wrappers\tao\tao_idl\be\be_interface.cpp:748

#if !defined (_INSTRUCTION_INSTRUCTDATAREADER__VAR_OUT_CH_)
#define _INSTRUCTION_INSTRUCTDATAREADER__VAR_OUT_CH_

  class instructDataReader;
  typedef instructDataReader *instructDataReader_ptr;
  typedef TAO_Objref_Var_T<instructDataReader> instructDataReader_var;
  typedef TAO_Objref_Out_T<instructDataReader> instructDataReader_out;
  

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:40

  class  instructDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // d:\opendds\ace_wrappers\tao\tao_idl\be\be_type.cpp:304

    typedef instructDataReader_ptr _ptr_type;
    typedef instructDataReader_var _var_type;
    typedef instructDataReader_out _out_type;

    // The static operations.
    static instructDataReader_ptr _duplicate (instructDataReader_ptr obj);

    static void _tao_release (instructDataReader_ptr obj);

    static instructDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static instructDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static instructDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::instruction::instructSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::instruction::instructSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::instruction::instructSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::instruction::instructSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::instruction::instruct & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::instruction::instruct & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::instruction::instructSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::instruction::instructSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::instruction::instructSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::instruction::instructSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::instruction::instructSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::instruction::instructSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::instruction::instructSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::instruction::instructSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::instruction::instructSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::instruction::instruct & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::instruction::instruct & instance_data) = 0;

    // TAO_IDL - Generated from
    // d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_ch.cpp:137

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    instructDataReader (void);

    

    virtual ~instructDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (instructDataReader (const instructDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (instructDataReader (instructDataReader &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (instructDataReader &operator= (const instructDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (instructDataReader &operator= (instructDataReader &&))
#endif /* ACE_HAS_CPP11 */
  };

// TAO_IDL - Generated from
// d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_module\module_ch.cpp:64

} // module instruction

// TAO_IDL - Generated from
// d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_arg_traits.cpp:66

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_traits.cpp:60

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_INSTRUCTION_INSTRUCTTYPESUPPORT__TRAITS_)
#define _INSTRUCTION_INSTRUCTTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::instruction::instructTypeSupport>
  {
    static ::instruction::instructTypeSupport_ptr duplicate (
        ::instruction::instructTypeSupport_ptr p);
    static void release (
        ::instruction::instructTypeSupport_ptr p);
    static ::instruction::instructTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::instruction::instructTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_INSTRUCTION_INSTRUCTDATAWRITER__TRAITS_)
#define _INSTRUCTION_INSTRUCTDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::instruction::instructDataWriter>
  {
    static ::instruction::instructDataWriter_ptr duplicate (
        ::instruction::instructDataWriter_ptr p);
    static void release (
        ::instruction::instructDataWriter_ptr p);
    static ::instruction::instructDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::instruction::instructDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_INSTRUCTION_INSTRUCTDATAREADER__TRAITS_)
#define _INSTRUCTION_INSTRUCTDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::instruction::instructDataReader>
  {
    static ::instruction::instructDataReader_ptr duplicate (
        ::instruction::instructDataReader_ptr p);
    static void release (
        ::instruction::instructDataReader_ptr p);
    static ::instruction::instructDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::instruction::instructDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// d:\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:1686
#if defined (__ACE_INLINE__)
#include "instructionTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

