// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.12
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "instructionC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "instructionC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:49

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const instruction::instruct &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.vehicle.in ()) &&
    (strm << _tao_aggregate.action.in ()) &&
    (strm << _tao_aggregate.id) &&
    (strm << _tao_aggregate.dirction.in ()) &&
    (strm << _tao_aggregate.distance);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    instruction::instruct &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.vehicle.out ()) &&
    (strm >> _tao_aggregate.action.out ()) &&
    (strm >> _tao_aggregate.id) &&
    (strm >> _tao_aggregate.dirction.out ()) &&
    (strm >> _tao_aggregate.distance);
}

TAO_END_VERSIONED_NAMESPACE_DECL



